### PR TITLE
added cleanup handler

### PR DESCRIPTION
**Pull request by Jakobeha**
Adds a function `rirCleanup` which will be called when R exits.

Would be used by https://github.com/reactorlabs/rir/pull/474.

### CODE REVIEW

**Comment by o-** [comment]
shouldn't this be doable with `onExit`?

**Comment by Jakobeha** [comment]
Not sure what you're referring to, there's an `onExit` function but it's in code related to graphics, there's no `onExit` function in RIR.

**Comment by Jakobeha** [comment]
I see r has an on.exit I could use in rir.R, but that could get overridden in later R code

**Comment by o-** [comment]
yes I meant the R onexit handler. since we only need this for running our own, controlled experiments (where we can ensure that the handler is not overwriten)  I would prefer using the normal onexit handler.

**Pull request closed without merging**
